apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Base64 encoded password - REPLACE WITH YOUR PASSWORD
  # To encode: echo -n "your-password" | base64
  password: <BASE64_ENCODED_PASSWORD>
  # Base64 encoded root password - REPLACE WITH YOUR ROOT PASSWORD  
  # To encode: echo -n "your-root-password" | base64
  root-password: <BASE64_ENCODED_ROOT_PASSWORD>