apiVersion: v1
kind: Service
metadata:
  name: proxy-nodeport
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort